server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0

spring:
  cloud:
    config:
      uri: ${CONFIG_SERVER_URL:http://localhost:8888}