server:
  address: 0.0.0.0
  port: 8761

spring:
  application:
    name: serviceRegistry

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0
