server:
  address: 127.0.0.1
  port: 8888

spring:
  application:
    name: configServer
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kangliqi/cloud-demo
          searchPaths: .cloud-demo-config
